"""Second migration

Revision ID: 92ae4b390caa
Revises: b4d67696057a
Create Date: 2025-03-15 18:53:45.776982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92ae4b390caa'
down_revision: Union[str, None] = 'b4d67696057a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_url')
    op.drop_table('user')
    op.drop_index('ix_urls_custom_url', table_name='urls')
    op.drop_index('ix_urls_secret_key', table_name='urls')
    op.drop_index('ix_urls_target_url', table_name='urls')
    op.drop_table('urls')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('urls_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('custom_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('secret_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('time_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('clicks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='urls_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_urls_target_url', 'urls', ['target_url'], unique=False)
    op.create_index('ix_urls_secret_key', 'urls', ['secret_key'], unique=True)
    op.create_index('ix_urls_custom_url', 'urls', ['custom_url'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('username', name='user_username_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_url',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('link_created', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('link_time_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['link_created'], ['urls.custom_url'], name='user_url_link_created_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_url_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'link_created', name='user_url_pkey')
    )
    # ### end Alembic commands ###
